#
# Generated by the NeXT Interface Builder.
#
# NOTE: Do NOT change this file -- Interface Builder maintains it.
#
# Put all of your customizations in files called Makefile.preamble
# and Makefile.postamble (both optional), and Makefile will include them.
#

NAME = a2

INTERFACES = a2.nib
CLASSES = WozView.m
MFILES = a2_main.m temp.m
CFILES = a2.c cli.c commands.c curses.c disk.c dos.c hgrconv.c hgrtable.c \
         jump.c main.c mem.c parse.c prodos.c screen.c table.c tbl.c \
         vidout.c
HFILES = a2.h cli.h hgrconv.h hgrtable.h


SOURCEMODE = 444

LIBS = -lcurses -ltermcap\
	-lNeXT_s -lsys_s
DEBUG_LIBS = $(LIBS)
PROF_LIBS = -lcurses -ltermcap\
	-lNeXT_p -lsys_p

MAKEFILEDIR = /usr/lib/nib
ICONSECTIONS =	-sectcreate __ICON app /usr/lib/nib/default_app_icon.tiff

INSTALLDIR = $(HOME)/Apps
INSTALLFLAGS = -c -s -m 755

-include Makefile.preamble

include $(MAKEFILEDIR)/app.make

-include Makefile.postamble

-include Makefile.dependencies
